### ISSUE TITLE
mousai fails to build with rust-libadwaita 0.7.2

### ISSUE THREAD

**Issue by jbicha** [SeaDve/Mousai#157]
**Affected version**

* mousai 0.7.8
* rustc 1.85.0
* rust-libadwaita 0.7.2
* Debian Unstable

**Bug summary**

mousai is failing to build. This was noticed after the update of rust-libadwaita from 0.7.1 to 0.7.2. Therefore this may be similar to https://gitlab.gnome.org/GNOME/gnome-tour/-/issues/61

**Full build log**
Linked from https://bugs.debian.org/1101634

**Log excerpt**

```
rror[E0277]: the trait bound `information_row::InformationRow: libadwaita::prelude::IsA<ActionRow>` is not satisfied
  --> src/window/information_row.rs:50:10
   |
50 |     impl ActionRowImpl for InformationRow {}
   |          ^^^^^^^^^^^^^ the trait `libadwaita::prelude::IsA<ActionRow>` is not implemented for `information_row::InformationRow`
   |
   = help: the following other types implement trait `libadwaita::prelude::IsA<T>`:
             `information_row::InformationRow` implements `libadwaita::prelude::IsA<PreferencesRow>`
             `information_row::InformationRow` implements `libadwaita::prelude::IsA<gtk4::Widget>`
             `information_row::InformationRow` implements `libadwaita::prelude::IsA<information_row::InformationRow>`
             `information_row::InformationRow` implements `libadwaita::prelude::IsA<libadwaita::glib::Object>`
note: required by a bound in `libadwaita::subclass::action_row::ActionRowImpl`
  --> /usr/share/cargo/registry/libadwaita-0.7.2/src/subclass/action_row.rs:7:68
   |
7  | pub trait ActionRowImpl: PreferencesRowImpl + ObjectSubclass<Type: IsA<ActionRow>> {
   |                                                                    ^^^^^^^^^^^^^^ required by this bound in `ActionRowImpl`

error[E0277]: the trait bound `ActionRow: From<information_row::InformationRow>` is not satisfied
  --> src/window/information_row.rs:50:10
   |
50 |     impl ActionRowImpl for InformationRow {}
   |          ^^^^^^^^^^^^^ the trait `From<information_row::InformationRow>` is not implemented for `ActionRow`
   |
   = help: the following other types implement trait `From<T>`:
             `ActionRow` implements `From<ComboRow>`
             `ActionRow` implements `From<SpinRow>`
             `ActionRow` implements `From<SwitchRow>`
   = note: required for `information_row::InformationRow` to implement `Into<ActionRow>`
   = note: required for `<information_row::imp::InformationRow as libadwaita::subclass::prelude::ObjectSubclass>::Type` to implement `libadwaita::prelude::IsA<ActionRow>`
note: required by a bound in `libadwaita::subclass::action_row::ActionRowImpl`
  --> /usr/share/cargo/registry/libadwaita-0.7.2/src/subclass/action_row.rs:7:68
   |
7  | pub trait ActionRowImpl: PreferencesRowImpl + ObjectSubclass<Type: IsA<ActionRow>> {
   |                                                                    ^^^^^^^^^^^^^^ required by this bound in `ActionRowImpl`

For more information about this error, try `rustc --explain E0277`.
```
